### ISSUE TITLE
How to arrange the "row order" in plotHeatmap() or "gene order" in plotExpression() for scater package? 

### ISSUE THREAD

**Issue by crebli** [crebli/-row-order-in-plotHeatmap-and-genes-order-in-plotExpression-in-scater-package#1]
For the function plotExpression() in package scater, we are unable to arrange the order of genes. The default order of a list of genes are arranged just in alphabetical order.  
It's the same problem for function plotHeatmap() in package scater, that a list of genes are ploted and displayed in alphabetical order if we set argument "cluster_rows = FALSE". 
So we recommend to set up arguments to manipulate the gene order in these two  functions in package scater: plotExpression() and plotHeatmap().

**Comment by LTLA** [comment]
I meant to put it on the _scater_ GitHub repository, see https://github.com/davismcc/scater.

**Comment by crebli** [comment]
Sorry for my mistake. Now I raise the question in github.com/davismcc/scater.
Thank you very much.


Best


Yinchuan Li
















At 2020-04-16 15:47:35, "Aaron Lun" <notifications@github.com> wrote:

I meant to put it on the scater GitHub repository, see https://github.com/davismcc/scater.
